# Generated by Django 3.0 on 2021-10-02 12:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_models', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ppu',
            name='deadlines',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ppu',
            name='vned',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='vned', to=settings.AUTH_USER_MODEL),
        ),
    ]
