# Generated by Django 3.0 on 2021-10-02 12:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_models', '0002_auto_20211002_1229'),
    ]

    operations = [
        migrations.DeleteModel(
            name='VnedPPU',
        ),
    ]
